"""initial

Revision ID: e3f6174b1155
Revises: 
Create Date: 2026-06-01 17:28:15.921159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3f6174b1155'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('quotes_agent_id_fkey', 'quotes', type_='foreignkey')
    op.alter_column('agents', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.drop_constraint(op.f('agents_email_key'), 'agents', type_='unique')
    op.alter_column('quotes', 'id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('quotes', 'agent_id',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=32),
               existing_nullable=True)
    op.create_foreign_key('quotes_agent_id_fkey', 'quotes', 'agents', ['agent_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('quotes_agent_id_fkey', 'quotes', type_='foreignkey')
    op.alter_column('quotes', 'agent_id',
               existing_type=sa.String(length=32),
               type_=sa.INTEGER(),
               existing_nullable=True)
    op.alter_column('quotes', 'id',
               existing_type=sa.String(length=32),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_unique_constraint(op.f('agents_email_key'), 'agents', ['email'], postgresql_nulls_not_distinct=False)
    op.alter_column('agents', 'id',
               existing_type=sa.String(length=32),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.create_foreign_key('quotes_agent_id_fkey', 'quotes', 'agents', ['agent_id'], ['id'])
    # ### end Alembic commands ###
